swagger: '2.0'
info:
  title:  "{{title}}"
  description: 'DB self service'
  version: "0.1"

consumes:
  - application/json
produces:
  - application/json
paths:
  /people:
    get:
      operationId: app.routes.get_people
      tags: [DB]
      description:
        Gets list of `DB` objects.
      responses:
        '200':
          description: Successful response
          schema:
            title: ArrayOfpbjects
            type: array
            items:
              $ref: '#/definitions/db_rows'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /people/{lastname}:
    get:
      operationId: app.routes.get_by_last_name
      tags: [DB]
      description:
        Gets list of `DB` objects.
      parameters:
        - $ref: '#/parameters/last'
      responses:
        '200':
          description: Successful response
          schema:
            title: ArrayOfpbjects
            type: object
            items:
              $ref: '#/definitions/Person'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

parameters:
  last:
    name: lastname
    description: last name
    in: path
    type: string
    required: true

definitions:
  db_rows:
    type: object
    properties:
      name:
        type: string
      members:
        type: array
        items:
          $ref: '#/definitions/Person'
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  Person:
    type: object
    properties:
      City:
        type: string
      Firstname:
        type: string
      Lastname:
        type: string
      PersonID:
        type: integer
        format: int32
